# Generated by Django 5.1.3 on 2024-12-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_users", "0003_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
