# Generated by Django 5.1.3 on 2024-12-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_message_mailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("Launched", "Запущена"), ("Completed", "Завершена")],
                default="created",
                verbose_name="Статус рассылки",
            ),
        ),
    ]
