# Generated by Django 5.1.3 on 2024-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0003_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                related_name="recipients", to="mailing_service.recipientmailing", verbose_name="Получатели"
            ),
        ),
    ]
