# Generated by Django 5.1.3 on 2024-12-04 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0004_alter_mailing_recipients"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime_attempt", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(verbose_name="Статус рассылки")),
                ("mail_server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mailing",
                        to="mailing_service.mailing",
                    ),
                ),
            ],
        ),
    ]
