# Generated by Django 5.1.3 on 2024-12-05 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_mailingattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_attempt", models.IntegerField(verbose_name="Всего попыток рассылки")),
                ("successful_attempt", models.IntegerField(verbose_name="Успешных попыток рассылки")),
                ("unsuccessful_attempt", models.IntegerField(verbose_name="Неуспешных попыток рассылки")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
